services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: laravel
        uid: 1000
    image: laravel-12-app
    container_name: laravel-12-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel-network

  nginx:
    image: nginx:alpine
    container_name: laravel-12-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network
    depends_on:
      - app
      - mysql

  mysql:
    image: mysql:8.0
    container_name: laravel-12-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-network

  node:
    image: node:20-alpine  # Cambiado a Node.js 22
    container_name: laravel-12-node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "5173:5173"
    tty: true
    stdin_open: true
    networks:
      - laravel-network
    depends_on:
      - app

volumes:
  mysql_data:

networks:
  laravel-network:
    driver: bridge